get func add
Sublet-K/Sublet pull request #16
Opened 2023-09-23 21:05 UTC by cjfghk5697

가장 중요한 핵심이 아마

* user field 추가
* key가 아닌 user id로 검색 -> get할때 user id로 검색가능하게 하려고
ex) github.com/cjfghk5697

이외에 궁금한 내용과 이슈는 디코나 카톡으로 얘기해야할듯...

2023-09-23 21:31 UTC, cjfghk5697 commented
그 이거 아마 디코로 얘기해야할듯.. 할수록 복잡해져서 나도 정리가 필요해졌어 ㅋㅋㅋㅋㅋㅋ

2023-09-24 02:51 UTC, bagger3025 requested changes
이제 User에서 중요한 건 로그인/로그아웃, 그리고 post의 작성자로 연동하는 것 정도인 것 같은데
화이팅이야!

2023-09-24 02:51 UTC, bagger3025 commented on backend/src/modules/user/user.controller.ts
> +  constructor(private readonly db: MongodbService) {}
userService는 그대로 두고 거기에서 로직을 처리하도록 만들어야돼

userService가 mongodbservice를 불러와서 처리하도록 바꾸는 게 맞는듯

2023-09-24 02:51 UTC, bagger3025 commented on backend/package.json
> +    "mongodb": "^6.1.0",
아마 사용하지 않을 것 같으니 삭제하는 게 좋을듯?

2023-09-24 02:51 UTC, bagger3025 commented on backend/prisma/schema.prisma
> +  password String
이걸 나누는 건 좋은데 나눴으면 원래 User에 있는 사람과 연동이 되어야 의미 있을 것 같아

보안 관련해서 나눈 거라면 https://www.prisma.io/docs/concepts/components/prisma-client/client-extensions/extension-examples#examples
에서 obfuscated-fields 참고해서 다시 합쳐도 될 것 같고

내 생각에는 굳이 나눌 필요 없는 것 같음

2023-09-27 04:40 UTC, bagger3025 reviewed
일단은 이정도..? 많이 한 거 보니까 고생 많았습니다

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/auth/auth.controller.ts
> +    req.logOut(function (err, next) {
next를 콘솔에 찍어보니까 undefined이던데 이렇게 하는 건 아닌 것 같음
https://www.passportjs.org/concepts/authentication/logout/

다시 한 번 보는 게 좋을듯?

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/auth/auth.controller.ts
> +    req.logOut(function (err) {
next 이 방식 맞는 것 같은데..? 왜 바꾼거야?

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/auth/auth.controller.ts
> +  @UseGuards(LocalGuard)
LocalGuard가 여기 있으니까 다시 id와 password를 필요로 하는 것 같음

없어지는 게 맞는 것 같아

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/auth/auth.controller.ts
> +      res.redirect('/');
redirect를 시키니까 Hello World가 나오는데, 웹페이지를 서비스하는 게 아닌 만큼 없어져도 될 듯

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/auth/auth.controller.ts
> +      res.redirect('/');
backend에서 / 주소로 리다이렉트하는 거라 Hello World!가 나오는 거니까

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/user/user.service.ts
> +    return await this.prisma.user.findMany();
prismaService를 가져와서 db작업을 처리하는 건 MongodbService에 맡기고 그걸 가져와야 할 것 같아

controller -> service -> mongodbservice -> prismaservice 이 순이 되어야 할 듯

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/user/dto/user.dto.ts
> +  @IsOptional()
delete가 optional이어버리면 true를 제공했을 때 지워진 상태가 되니까 비워져 있어야 할 것 같아

IsEmpty()로 바뀌던가 이 class에서 빠져야 할 듯

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/mongodb/mongodb.service.ts
> - async createUser(data: UserCreateDto) {
이거 맞는 것 같은데..?

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/user/user.service.ts
> +    return await this.prisma.user.findMany();
findMany할 때에도 delete가 false인지를 검사하는 조건을 추가해주면 좋을듯

2023-09-27 04:40 UTC, bagger3025 commented on backend/src/modules/user/user.service.ts
> +    return await this.prisma.user.findFirst({
이것도 mongodbService로 옮기고 그걸 부르는 식으로 가고

deleted가 false인지를 검사해줘야 할듯

2023-09-28 17:45 UTC, cjfghk5697 commented
답변 감사합니다 하나하나 처리해보겠습니다

2023-09-28 17:48 UTC, cjfghk5697 commented
하나하나 처리할때마다 comment 달아서 다 완성되면 디코에 다시 올리겠습니다! 친절한 답변 정말 감사합니다 ㅎㅎ

2023-09-29 03:48 UTC, bagger3025 commented on backend/src/modules/auth/auth.controller.ts
> +  @UseGuards(LocalGuard)
아직 해결 안 됐어요.. 다시 봐주세요

2023-09-29 03:56 UTC, bagger3025 commented
1. mongodb에서 delete가 false인지 검사하기 - 지워졌다면 사실상 없는 것이기 때문
2. 이 delete 필드가 문제인데, 우리만 볼 수 있게 하고 입력이나 출력에는 전혀 보이지 않아야 돼
    사용자가 어떤 방식으로도 이 데이터를 변하게 하면 안 되고, 데이터를 보여줄 때에도 이걸 없앨 수 있는 방법이 있어야 돼
3. LocalGuard가 있으면 id/password를 요구하기 때문에 logOut에서 요구하면 안 되는 guard임

2023-09-30 17:37 UTC, cjfghk5697 commented
> 1. mongodb에서 delete가 false인지 검사하기 - 지워졌다면 사실상 없는 것이기 때문
> 2. 이 delete 필드가 문제인데, 우리만 볼 수 있게 하고 입력이나 출력에는 전혀 보이지 않아야 돼
>    사용자가 어떤 방식으로도 이 데이터를 변하게 하면 안 되고, 데이터를 보여줄 때에도 이걸 없앨 수 있는 방법이 있어야 돼
> 3. LocalGuard가 있으면 id/password를 요구하기 때문에 logOut에서 요구하면 안 되는 guard임
> 
> 화이팅!!

감사합니다 ㅎㅎ 고쳐보겠습니다!

2023-10-02 21:57 UTC, cjfghk5697 commented
해결 완 행복해

2023-10-03 09:29 UTC, bagger3025 commented
오케이 테스트 실패하는 것만 고치고 일단 merge 해봅시다

2023-10-03 13:49 UTC, cjfghk5697 commented
오키 일단 테스트코드 좀 공부할게

2023-10-11 00:56 UTC, bagger3025 commented
오케이 일단 merge하고 나중에 발생하는 문제는 따로 처리해봅시다
그리고 github에 올리지 않고도 `npm run test:e2e`로 테스트해볼 수 있음
package.json에 `npm run`으로 할 수 있는 명령어들 있으니 참고해보면 좋을 것 같아

2023-10-11 00:56 UTC, bagger3025 approved these changes

2023-10-11 00:57 UTC, merged

2023-10-11 03:14 UTC, cjfghk5697 commented
맞아 npm run test:e2e로 계속 해봤는데, vscode내에서는 prisma랑 연결되어 있어서 테스트 통과가 되는데 깃허브에서만 안되었어

2023-10-12 04:12 UTC, bagger3025 commented
아하 오케이